# Generated by Django 3.1.1 on 2020-09-22 21:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200915_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[[3, 'C'], [2, 'PHP'], [1, 'Python']], default='', max_length=5, null=True),
        ),
    ]
