# Generated by Django 3.1.1 on 2020-09-28 04:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200923_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='user'),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='user'),
        ),
    ]
