# Generated by Django 3.1.1 on 2020-09-28 05:18

from django.db import migrations, models
import django_extensions.db.fields
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200928_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(default=post.models.generate_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=post.models.generate_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
