# Generated by Django 3.1.1 on 2020-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=20)),
                ('detail', models.TextField(max_length=500, null=True)),
                ('site', models.URLField(null=True)),
            ],
        ),
    ]
