# Generated by Django 3.1.1 on 2020-09-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200920_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
