# Generated by Django 3.1.1 on 2020-09-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('useraccount', '0002_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='user_tags', to='tags.Tag'),
        ),
    ]
