# Generated by Django 3.1.1 on 2020-09-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20200915_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_img.png', upload_to='profiles'),
        ),
    ]
