# Generated by Django 3.1.1 on 2020-09-16 15:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20200915_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='user.username'),
        ),
    ]
