# Generated by Django 3.1.1 on 2020-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('useraccount', '0007_auto_20200916_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', related_name='user_tags', to='tags.Tag'),
        ),
    ]
