# Generated by Django 3.1.1 on 2020-09-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20200916_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
    ]
