# Generated by Django 3.1.1 on 2020-09-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('useraccount', '0009_remove_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', related_name='user_tags', to='tags.Tag'),
        ),
    ]
