# Generated by Django 3.1.1 on 2020-09-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to='profiles'),
        ),
    ]
