# Generated by Django 3.1.1 on 2020-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200920_0254'),
        ('useraccount', '0011_auto_20200920_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_tags', to='tags.Tag'),
        ),
    ]
