# Generated by Django 3.1.1 on 2020-09-21 05:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_auto_20200920_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[[1, 'Python'], [2, 'PHP']], default='', max_length=3, null=True),
        ),
    ]
