# Generated by Django 3.1.1 on 2020-09-21 05:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_auto_20200921_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[[2, 'PHP'], [1, 'Python']], default='', max_length=3, null=True),
        ),
    ]
