# Generated by Django 3.1.1 on 2020-09-22 21:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_auto_20200921_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_img.png', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[[3, 'C'], [2, 'PHP'], [1, 'Python']], default='', max_length=5, null=True),
        ),
    ]
