# Generated by Django 3.1.1 on 2020-10-10 17:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_auto_20200928_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[[3, 'C'], [4, 'Django'], [2, 'PHP'], [1, 'Python']], default='', max_length=7, null=True),
        ),
    ]
