export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADFAIL = 'USER_LOADFAIL';

export const USER_UPDATING= 'USER_UPDATING';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_UPDATEFAIL = 'USER_UPDATEFAIL';

export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_LOADED = 'PROFILE_LOADED'
export const PROFILE_LOADFAIL = 'PROFILE_LOADFAIL'

export const PROFILE_UPDATING = 'PROFILE_UPDATING'
export const PROFILE_UPDATED = 'PROFILE_UPDATED'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'

// Tags 
export const TAGS_LOADING = 'TAGS_LOADING'
export const TAGS_LOADED = 'TAGS_LOADED'
export const TAGS_LOAD_FAIL = 'TAGS_LOAD_FAIL'

// Questions

export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const QUESTIONS_LOADED = "QUESTIONS_LOADED";
export const QUESTION_LOAD_FAIL = "QUESTION_LOAD_FAIL";