export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADFAIL = 'USER_LOADFAIL';

export const USER_UPDATING= 'USER_UPDATING';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_UPDATEFAIL = 'USER_UPDATEFAIL';

export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_LOADED = 'PROFILE_LOADED'
export const PROFILE_LOADFAIL = 'PROFILE_LOADFAIL'

export const CHANGE_PROFILE_PICTURE_LOADING = "CHANGE_PROFILE_PICTURE_LOADING";
export const CHANGE_PROFILE_PICTURE_SUCCESS = "CHANGE_PROFILE_PICTURE_SUCCESS";
export const CHANGE_PROFILE_PICTURE_FAIL = "CHANGE_PROFILE_PICTURE_FAIL";

